"""new column email in Resumes table

Revision ID: e11174b29456
Revises: dd94d9c738c0
Create Date: 2026-07-29 08:24:15.707265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11174b29456'
down_revision: Union[str, Sequence[str], None] = 'dd94d9c738c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidates', ['id'])
    op.add_column('resumes', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'resumes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='unique')
    op.drop_column('resumes', 'email')
    op.drop_constraint(None, 'candidates', type_='unique')
    # ### end Alembic commands ###
